import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The item list below is generated by docusaurus-plugin-openapi-docs from
// static/openapi/dz-api.yaml. Regenerate it with `npm run gen-api`.
//
// The require is guarded because `gen-api` has to load this config before the
// generated file exists, so a hard import would deadlock a clean checkout.
let apiSpecSidebar: any[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  apiSpecSidebar = require('./docs-api-spec/sidebar').default ?? [];
} catch {
  apiSpecSidebar = [];
}

const sidebars: SidebarsConfig = {
  apiSpecSidebar: [
    {
      type: 'category',
      label: 'DZ Enterprise API v1',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'DZ Enterprise API',
        description:
          'Reference generated from the OpenAPI 3.0 specification. The same API is documented by hand under API Documentation; this section is the machine-generated view of the contract.',
        slug: '/',
      },
      items: apiSpecSidebar,
    },
  ],
};

export default sidebars;
