import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import ApiLayout from '@site/src/components/ApiDocs/ApiLayout';
import EndpointSection from '@site/src/components/ApiDocs/EndpointSection';
import CodeTabs from '@site/src/components/ApiDocs/CodeTabs';
import ParamTable from '@site/src/components/ApiDocs/ParamTable';
import FieldTable from '@site/src/components/ApiDocs/FieldTable';
import ResponseBlock from '@site/src/components/ApiDocs/ResponseBlock';
import styles from '@site/src/components/ApiDocs/ApiLayout.module.css';
import { PROSE, INLINE_CODE } from '@site/src/components/ApiDocs/textStyles';

// ─── Shared sample data ───────────────────────────────────────────────────────
// Allocations sum to 100, matching the rule documented in the request body.
const PORTFOLIO = {
  portfolio_id: 'prt_BNPParibas_001',
  name: 'BHMS Portfolio BNP Paribas',
  strategy: 'loan benchmarking',
  currency: 'GBP',
  total_value: 20000000.00,
  status: 'active',
  accounts: [
    {
      id: 'acc_007',
      name: 'BHMS Account 007',
      owner_id: 'james_b',
      type: 'fee',
      allocation_pct: 58.93,
    },
    {
      id: 'acc_8901',
      name: 'US PNGN Account 8901',
      owner_id: 'felix_l',
      type: 'custody',
      allocation_pct: 41.07,
    },
  ],
  created_at: '2026-02-01T08:00:00Z',
  updated_at: '2026-03-25T11:15:00Z',
};

const PORTFOLIO_LIST = {
  data: [
    PORTFOLIO,
    {
      ...PORTFOLIO,
      portfolio_id: 'prt_BNY_897',
      name: 'Derivatives Portfolio',
      strategy: 'conservative',
      total_value: 3420000.00,
    },
  ],
  total: 2,
  limit: 20,
  offset: 0,
};

const PORTFOLIO_STATUSES = 'active, paused, closed';

const ALLOCATION_FIELDS = [
  { name: 'id', type: 'string', description: 'Unique Account identifier.' },
  { name: 'name', type: 'string', description: 'Account display name, denormalized for convenience.' },
  { name: 'owner_id', type: 'string', description: 'Identifier of the user who owns the Account.' },
  { name: 'type', type: 'string', description: 'Account type. One of: trading, operating, custody, fee.' },
  { name: 'allocation_pct', type: 'number', description: 'Share of the Portfolio held in this Account. All allocations sum to 100.' },
];

const PORTFOLIO_FIELDS = [
  { name: 'portfolio_id', type: 'string', description: 'Unique Portfolio identifier, generated by the API.' },
  { name: 'name', type: 'string', description: 'Descriptive name shown in the UI.' },
  { name: 'strategy', type: 'string', description: 'Investment strategy label, for example "loan benchmarking" or "conservative".' },
  { name: 'currency', type: 'string', description: 'ISO 4217 base currency. Fixed at creation.' },
  { name: 'total_value', type: 'number', description: 'Sum of all Account balances, in the major unit of currency.' },
  { name: 'status', type: 'string', description: `One of: ${PORTFOLIO_STATUSES}.` },
  { name: 'accounts', type: 'array', description: 'Accounts allocated to this Portfolio. See the allocation object below.' },
  { name: 'created_at', type: 'string', description: 'RFC 3339 timestamp in UTC.' },
  { name: 'updated_at', type: 'string', description: 'RFC 3339 timestamp in UTC of the last change.' },
];

const LIST_FIELDS = [
  { name: 'data', type: 'array', description: 'The page of Portfolio objects. Empty when nothing matches, never null.' },
  { name: 'total', type: 'integer', description: 'Total Portfolios matching the filter, across all pages.' },
  { name: 'limit', type: 'integer', description: 'The limit applied to this response, after clamping to 100.' },
  { name: 'offset', type: 'integer', description: 'The offset applied to this response.' },
];

// ─── Snippets ─────────────────────────────────────────────────────────────────
const LIST_CURL = `curl -X GET "https://api.dzenterprise.io/v1/portfolios?strategy=loan%20benchmarking&limit=20" \\
  -H "Authorization: Bearer {access_token}" \\
  -H "Content-Type: application/json"`;

const LIST_PYTHON = `import requests

BASE_URL = "https://api.dzenterprise.io/v1"

params  = {"strategy": "loan benchmarking", "limit": 20}
headers = {"Authorization": "Bearer {access_token}"}

response = requests.get(f"{BASE_URL}/portfolios", params=params, headers=headers)
print(response.json())`;

const LIST_JS = `const BASE_URL = 'https://api.dzenterprise.io/v1';

const query = new URLSearchParams({ strategy: 'loan benchmarking', limit: 20 });

const response = await fetch(\`\${BASE_URL}/portfolios?\${query}\`, {
  headers: { Authorization: \`Bearer \${accessToken}\` },
});

const { data } = await response.json();
console.log(data);`;

const GET_CURL = `curl -X GET "https://api.dzenterprise.io/v1/portfolios/prt_BNPParibas_001" \\
  -H "Authorization: Bearer {access_token}"`;

const GET_PYTHON = `import requests

BASE_URL     = "https://api.dzenterprise.io/v1"
PORTFOLIO_ID = "prt_BNPParibas_001"

headers = {"Authorization": "Bearer {access_token}"}

response = requests.get(f"{BASE_URL}/portfolios/{PORTFOLIO_ID}", headers=headers)
print(response.json())`;

const GET_JS = `const BASE_URL = 'https://api.dzenterprise.io/v1';
const portfolioId = 'prt_BNPParibas_001';

const response = await fetch(\`\${BASE_URL}/portfolios/\${portfolioId}\`, {
  headers: { Authorization: \`Bearer \${accessToken}\` },
});

console.log(await response.json());`;

const CREATE_CURL = `curl -X POST "https://api.dzenterprise.io/v1/portfolios" \\
  -H "Authorization: Bearer {access_token}" \\
  -H "Content-Type: application/json" \\
  -H "Idempotency-Key: 7c1d4a90-3b52-4f88-9e10-6d5a2b7c8e41" \\
  -d '{
    "name": "BHMS Portfolio BNP Paribas",
    "strategy": "loan benchmarking",
    "currency": "GBP",
    "accounts": [
      { "id": "acc_007",  "allocation_pct": 58.93 },
      { "id": "acc_8901", "allocation_pct": 41.07 }
    ]
  }'`;

const CREATE_PYTHON = `import uuid
import requests

BASE_URL = "https://api.dzenterprise.io/v1"

headers = {
    "Authorization": "Bearer {access_token}",
    "Content-Type": "application/json",
    "Idempotency-Key": str(uuid.uuid4()),
}

payload = {
    "name": "BHMS Portfolio BNP Paribas",
    "strategy": "loan benchmarking",
    "currency": "GBP",
    "accounts": [
        {"id": "acc_007",  "allocation_pct": 58.93},
        {"id": "acc_8901", "allocation_pct": 41.07},
    ],
}

response = requests.post(f"{BASE_URL}/portfolios", json=payload, headers=headers)
print(response.json())`;

const CREATE_JS = `const BASE_URL = 'https://api.dzenterprise.io/v1';

const response = await fetch(\`\${BASE_URL}/portfolios\`, {
  method: 'POST',
  headers: {
    Authorization: \`Bearer \${accessToken}\`,
    'Content-Type': 'application/json',
    'Idempotency-Key': crypto.randomUUID(),
  },
  body: JSON.stringify({
    name: 'BHMS Portfolio BNP Paribas',
    strategy: 'loan benchmarking',
    currency: 'GBP',
    accounts: [
      { id: 'acc_007', allocation_pct: 58.93 },
      { id: 'acc_8901', allocation_pct: 41.07 },
    ],
  }),
});

console.log(await response.json());`;

const UPDATE_CURL = `curl -X PATCH "https://api.dzenterprise.io/v1/portfolios/prt_BNPParibas_001" \\
  -H "Authorization: Bearer {access_token}" \\
  -H "Content-Type: application/json" \\
  -d '{"name": "BHMS Core Growth Portfolio", "strategy": "moderate"}'`;

const UPDATE_PYTHON = `import requests

BASE_URL     = "https://api.dzenterprise.io/v1"
PORTFOLIO_ID = "prt_BNPParibas_001"

headers = {
    "Authorization": "Bearer {access_token}",
    "Content-Type": "application/json",
}

payload = {"name": "BHMS Core Growth Portfolio", "strategy": "moderate"}

response = requests.patch(
    f"{BASE_URL}/portfolios/{PORTFOLIO_ID}", json=payload, headers=headers
)
print(response.json())`;

const UPDATE_JS = `const BASE_URL = 'https://api.dzenterprise.io/v1';
const portfolioId = 'prt_BNPParibas_001';

const response = await fetch(\`\${BASE_URL}/portfolios/\${portfolioId}\`, {
  method: 'PATCH',
  headers: {
    Authorization: \`Bearer \${accessToken}\`,
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({ name: 'BHMS Core Growth Portfolio', strategy: 'moderate' }),
});

console.log(await response.json());`;

const DELETE_CURL = `curl -X DELETE "https://api.dzenterprise.io/v1/portfolios/prt_BNPParibas_001" \\
  -H "Authorization: Bearer {access_token}"`;

const DELETE_PYTHON = `import requests

BASE_URL     = "https://api.dzenterprise.io/v1"
PORTFOLIO_ID = "prt_BNPParibas_001"

headers = {"Authorization": "Bearer {access_token}"}

response = requests.delete(f"{BASE_URL}/portfolios/{PORTFOLIO_ID}", headers=headers)
print(response.status_code)  # 204`;

const DELETE_JS = `const BASE_URL = 'https://api.dzenterprise.io/v1';
const portfolioId = 'prt_BNPParibas_001';

const response = await fetch(\`\${BASE_URL}/portfolios/\${portfolioId}\`, {
  method: 'DELETE',
  headers: { Authorization: \`Bearer \${accessToken}\` },
});

console.log(response.status); // 204`;

// ─── Component ────────────────────────────────────────────────────────────────
export default function PortfoliosPage() {
  return (
    <Layout title="Portfolios | DZ API" description="CRUD endpoints for managing DZ Portfolios and their Account allocations.">
      <ApiLayout>
        {/* Page header */}
        <div className={styles.pageHeader}>
          <div className={styles.pageHeaderMeta}>Reference Data</div>
          <h1 className={styles.pageTitle}>Portfolios</h1>
          <p className={styles.pageSubtitle} style={{ marginBottom: '10px' }}>
            Create and manage Portfolios in your environment. The API supports full CRUD operations.
          </p>
          <p className={styles.pageSubtitle} style={{ marginBottom: '10px' }}>
            A Portfolio aggregates assets from one or more Accounts and tracks its own total value,
            currency, and investment strategy. To learn more about assembling Portfolios in the DZ
            environment, see the{' '}
            <Link to="/docs/stub" style={{ color: '#a78bfa' }}>Reference Data User Guide</Link>.
            Pagination, filtering, and idempotency follow the shared{' '}
            <Link to="/api/conventions" style={{ color: '#a78bfa' }}>Conventions</Link>.
          </p>

          <div className={styles.pageAccent} />
        </div>

        {/* ── GET /portfolios ── */}
        <EndpointSection
          id="list-portfolios"
          method="GET"
          path="/portfolios"
          title="List portfolios"
          description="Returns a paginated list of Portfolios. Filter by strategy or status to narrow results."
          noDivider
        >
          <ParamTable
            caption="Query parameters"
            params={[
              { name: 'strategy', type: 'string', required: false, description: 'Filter by investment strategy label, for example "loan benchmarking".' },
              { name: 'status', type: 'string', required: false, description: `Filter by status. One of: ${PORTFOLIO_STATUSES}.` },
              { name: 'limit', type: 'integer', required: false, description: 'Results per page. Default: 20. Maximum: 100.' },
              { name: 'offset', type: 'integer', required: false, description: 'Results to skip before the page starts. Default: 0.' },
            ]}
          />
          <CodeTabs curl={LIST_CURL} python={LIST_PYTHON} javascript={LIST_JS} />
          <FieldTable caption="Response fields" fields={LIST_FIELDS} />
          <ResponseBlock status={200} json={PORTFOLIO_LIST} />
        </EndpointSection>

        {/* ── GET /portfolios/:id ── */}
        <EndpointSection
          id="get-portfolio"
          method="GET"
          path="/portfolios/{portfolio_id}"
          title="Get portfolio by ID"
          description="Retrieves a single Portfolio, including its current total value and Account allocations."
        >
          <ParamTable
            caption="Path parameters"
            params={[
              { name: 'portfolio_id', type: 'string', required: true, description: 'Unique Portfolio ID, for example prt_BNPParibas_001.' },
            ]}
          />
          <CodeTabs curl={GET_CURL} python={GET_PYTHON} javascript={GET_JS} />
          <FieldTable caption="Response fields — Portfolio object" fields={PORTFOLIO_FIELDS} />
          <FieldTable caption="Response fields — accounts[] allocation object" fields={ALLOCATION_FIELDS} />
          <ResponseBlock status={200} json={PORTFOLIO} />
        </EndpointSection>

        {/* ── POST /portfolios ── */}
        <EndpointSection
          id="create-portfolio"
          method="POST"
          path="/portfolios"
          title="Create portfolio"
          description="Creates a Portfolio and attaches the supplied Account allocations."
        >
          <ParamTable
            caption="Request body"
            params={[
              { name: 'name', type: 'string', required: true, description: 'Descriptive name for the Portfolio.' },
              { name: 'strategy', type: 'string', required: true, description: 'Investment strategy label, for example "loan benchmarking".' },
              { name: 'currency', type: 'string', required: true, description: 'ISO 4217 base currency. Cannot be changed later.' },
              { name: 'accounts', type: 'array', required: false, description: 'Accounts investing in this Portfolio. Omit to create an empty Portfolio.' },
              { name: 'accounts[].id', type: 'string', required: true, description: 'Unique identifier of the Account. Required when accounts is supplied.' },
              { name: 'accounts[].allocation_pct', type: 'number', required: true, description: 'Share of the Portfolio held in this Account. All values must sum to exactly 100.' },
            ]}
          />

          <div style={{
            background: '#161a24',
            border: '1px solid #6a0aaf',
            borderLeft: '4px solid #6a0aaf',
            borderRadius: '6px',
            padding: '16px',
            margin: '0 0 20px',
            fontSize: '14px',
            color: '#e0e0e0',
            fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
            lineHeight: 1.6,
          }}>
            <strong>Note:</strong> <code style={INLINE_CODE}>portfolio_id</code> is generated by the
            API and must not be sent. The fields inside{' '}
            <code style={INLINE_CODE}>accounts[]</code> are required only when the{' '}
            <code style={INLINE_CODE}>accounts</code> array is supplied; if it is omitted, the
            Portfolio is created with no allocations. Allocations that do not sum to 100 are
            rejected with <code style={INLINE_CODE}>422 validation_failed</code>.
          </div>

          <CodeTabs curl={CREATE_CURL} python={CREATE_PYTHON} javascript={CREATE_JS} />
          <FieldTable caption="Response fields — Portfolio object" fields={PORTFOLIO_FIELDS} />
          <ResponseBlock status={201} json={PORTFOLIO} />
        </EndpointSection>

        {/* ── PATCH /portfolios/:id ── */}
        <EndpointSection
          id="update-portfolio"
          method="PATCH"
          path="/portfolios/{portfolio_id}"
          title="Update portfolio"
          description="Partially updates a Portfolio. Only the fields you send are modified."
        >
          <ParamTable
            caption="Path parameters"
            params={[
              { name: 'portfolio_id', type: 'string', required: true, description: 'Unique Portfolio ID.' },
            ]}
          />
          <ParamTable
            caption="Request body"
            params={[
              { name: 'name', type: 'string', required: false, description: 'New display name for the Portfolio.' },
              { name: 'strategy', type: 'string', required: false, description: 'Updated investment strategy label.' },
              { name: 'status', type: 'string', required: false, description: `New status. One of: ${PORTFOLIO_STATUSES}.` },
            ]}
          />
          <p style={{ ...PROSE, fontSize: '14px' }}>
            Allocations are not editable here. Change them by updating the Accounts attached to the
            Portfolio, so the sum can be revalidated as a whole.
          </p>
          <CodeTabs curl={UPDATE_CURL} python={UPDATE_PYTHON} javascript={UPDATE_JS} />
          <FieldTable caption="Response fields — Portfolio object" fields={PORTFOLIO_FIELDS} />
          <ResponseBlock
            status={200}
            json={{
              ...PORTFOLIO,
              name: 'BHMS Core Growth Portfolio',
              strategy: 'moderate',
              updated_at: '2026-04-05T10:00:00Z',
            }}
          />
        </EndpointSection>

        {/* ── DELETE /portfolios/:id ── */}
        <EndpointSection
          id="remove-portfolio"
          method="DELETE"
          path="/portfolios/{portfolio_id}"
          title="Remove portfolio"
          description="Permanently deletes a Portfolio and all its holdings records."
        >
          <ParamTable
            caption="Path parameters"
            params={[
              { name: 'portfolio_id', type: 'string', required: true, description: 'Unique Portfolio ID to delete.' },
            ]}
          />
          <p style={{ ...PROSE, fontSize: '14px' }}>
            A Portfolio with unsettled Transactions returns{' '}
            <code style={INLINE_CODE}>409 conflict</code>. The Accounts themselves are not deleted.
          </p>
          <CodeTabs curl={DELETE_CURL} python={DELETE_PYTHON} javascript={DELETE_JS} />
          <ResponseBlock status={204} json={null} />
        </EndpointSection>
      </ApiLayout>
    </Layout>
  );
}
