technical-writing:
  label: Technical Writing

api-documentation:
  label: API Documentation

knowledge-management:
  label: Knowledge Management

ai:
  label: AI

automation:
  label: Automation

docs-as-code:
  label: Docs as Code

fintech:
  label: Fintech

product-thinking:
  label: Product Thinking

leadership:
  label: Leadership

